app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

abc-rest-job:
    type: rest
    resource: "@AbcJobBundle/Resources/config/routing/rest-all.xml"
    prefix: /api