# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    demo_job:
        class: AppBundle\Job\DemoJob
        tags:
            -  { name: "abc.job", type: "say_hello", method: "sayHello" }
    scheduled_job:
        class: AppBundle\Job\DemoJob
        tags:
            -  { name: "abc.job", type: "scheduled_hello", method: "sayHello" }